[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_pgsql', 'php82Extensions.pgsql', 'php82Extensions.mbstring', 'php82Extensions.tokenizer', 'php82Extensions.xml', 'php82Extensions.ctype', 'php82Extensions.fileinfo', 'php82Extensions.bcmath']

[phases.install]
cmds = ['cd ksis-laravel && composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = ['cd ksis-laravel && php artisan config:cache && php artisan route:cache']

[start]
cmd = 'cd ksis-laravel && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'
