[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo_pgsql', 'php82Extensions.mbstring']

[phases.install]
cmds = ['cd ksis-laravel && composer install --no-dev --optimize-autoloader']

[start]
cmd = 'cd ksis-laravel && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'
